config:
  digestFunction: SHA256
  defaultActionTimeout: 3600
  maximumActionTimeout: 7200
  maxEntrySizeBytes: "4294967296"  # 4GB
  prometheusPort: 9090
  backplane:
    queues:
      - name: "cpu"
        allowUnmatched: true
        properties:
          - name: "min-cores"
            value: "*"
          - name: "max-cores"
            value: "*"
  server:
    name: "shard"
    recordBesEvents: true
    bytestreamTimeout: 7200
    casWriteTimeout: 7200
  worker:
    port: 8982

server:
  image:
    repository: docker.io/bazelbuild/buildfarm-server
  resources:
    limits:
      memory: 4Gi
      cpu: "2"
    requests:
      memory: 2Gi
      cpu: "1"
  replicaCount: 1

shardWorker:
  image:
    repository: docker.io/bazelbuild/buildfarm-worker
  resources:
    limits:
      memory: 4Gi
      cpu: "2"
    requests:
      memory: 2Gi
      cpu: "1"
  replicaCount: 2
  storage:
    size: 50Gi
